name: RealMinecraft
version: @version@
main: com.github.mcnagatuki.realminecraft.RealMinecraft
api-version: 1.15
authors: [ Nagatuki ]
description: Aho Shine

commands:
  real:
    description: enable or disable this plugin
    usage: /real <on|off|set|save|help>
    permission: real

permissions:
  real:
    default: op
