name: RealMinecraft
version: @version@
main: com.github.mc_nagatuki.realminecraft.RealMinecraft
api-version: 1.15
authors: [ McNagatuki ]
description: Aho Shine

commands:
  real:
    description: enable or disable this plugin
    usage: /<command> <on|off|set|save|help>
    default: op

  permissions:
    Real:
      default: op